name: Luxstra CD to Heroku - Dev

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
      - name: install npm dependencies
        run: (cd ./frontend && npm ci)
      - name: generate static assets
        run: (cd ./frontend && CI='' npm run build)
      - name: move static assets
        run: mv ./frontend/build ./src/main/resources
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: build with Gradle
        run: (./gradlew build jar && mv ./build/libs/Luxstra-1.0-SNAPSHOT.jar .)
      - name: Commit on the runner
        run:
          git config user.email "runner@github.com";
          git config user.name "Runner";
          git add -f ./src/main/resources/*;
          git add -f ./Luxstra-1.0-SNAPSHOT.jar;
          git commit -m "None"
      - name: Deploy to Heroku
        run: git push -f origin HEAD:dev-deploy